server:
  port: 8080
spring:
  application:
    name: spring-boot-legacy
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"

db:
  jdbcUrl: jdbc:mysql://localhost:3306
  username: root
  password: 123456
