server:
  port: 8101
spring:
  application:
    name: config-server
  profiles:
    active: git, jdbc
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/Wzefeng/config-repo
          search-paths: '{application}'
          force-pull: true
        jdbc:
          sql: "SELECT `key`, `value` FROM `t_config` WHERE application = ? AND profile = ? AND label = ?"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: debug